%% P09 - Analyze a CSV generated by matlab_temp_pid_host.m
clear; clc; close all;

baseDir=fileparts(mfilename('fullpath'));
outDir=fullfile(baseDir,'output');
files=dir(fullfile(outDir,'temp_*.csv'));
if isempty(files)
    error('No temp_*.csv found in examples/output. Run matlab_temp_pid_host.m first or copy a compatible CSV there.');
end
[~,idx]=max([files.datenum]);
file=fullfile(files(idx).folder,files(idx).name);
fprintf('Reading %s\n',file);
T=readtable(file);
required={'time_s','temp_C','sp_C','error','P','I','D','pid_pct','ssr'};
assert(all(ismember(required,T.Properties.VariableNames)),'Unexpected CSV columns.');

repo=fileparts(fileparts(fileparts(mfilename('fullpath'))));
addpath(fullfile(repo,'shared','matlab'));
M=response_metrics(T.time_s,T.temp_C,T.sp_C);
disp(M);

figure('Color','w');
tiledlayout(4,1);
nexttile; plot(T.time_s,T.sp_C,'--',T.time_s,T.temp_C,'LineWidth',1.1); grid on; ylabel('degC'); legend('SP','PV');
nexttile; plot(T.time_s,T.error,'LineWidth',1.0); grid on; ylabel('Error');
nexttile; plot(T.time_s,T.P,T.time_s,T.I,T.time_s,T.D,'LineWidth',1.0); grid on; ylabel('PID terms'); legend('P','I','D');
nexttile; yyaxis left; plot(T.time_s,T.pid_pct,'LineWidth',1.0); ylabel('Output (%)'); yyaxis right; stairs(T.time_s,T.ssr); ylabel('Command'); grid on; xlabel('Time (s)');

metricsFile=fullfile(outDir,['reanalyzed_metrics_' erase(files(idx).name,'.csv') '.csv']);
writetable(struct2table(M),metricsFile);
exportgraphics(gcf,fullfile(outDir,['reanalyzed_' erase(files(idx).name,'.csv') '.png']),'Resolution',180);
fprintf('Saved metrics and plot in %s\n',outDir);
