// P11 Arduino Mega speed PID, supervised/logged by MATLAB.
const uint8_t PWM_CW=5, PWM_CCW=6, ENC_A=2, ENC_B=3;
const float COUNTS_PER_REV=600.0f; const uint32_t SAMPLE_MS=50;
volatile long enc=0; volatile uint8_t prevState=0;
const int8_t QDEC[16]={0,-1,1,0,1,0,0,-1,-1,0,0,1,0,1,-1,0};
float sp=0,kp=.5f,ki=.2f,kd=0,maxPwm=180,integral=0,prevPv=0,lpf=0;bool running=false,pidInit=false;
uint32_t lastPing=0;const uint32_t HOST_TIMEOUT_MS=2500;bool timeoutReported=false;
void encISR(){uint8_t st=(digitalRead(ENC_A)<<1)|digitalRead(ENC_B);enc+=QDEC[(prevState<<2)|st];prevState=st;}
void motorStop(){analogWrite(PWM_CW,0);analogWrite(PWM_CCW,0);}
void motorWrite(float u){int pwm=(int)constrain(fabs(u),0,maxPwm);if(u>0){analogWrite(PWM_CCW,0);analogWrite(PWM_CW,pwm);}else if(u<0){analogWrite(PWM_CW,0);analogWrite(PWM_CCW,pwm);}else motorStop();}
void resetPID(){integral=0;pidInit=false;}
void command(String s){s.trim();int p=s.indexOf(',');if(p<0)return;String k=s.substring(0,p),v=s.substring(p+1);k.toUpperCase();if(k=="RUN"){running=v.toInt()!=0;if(running){lastPing=millis();timeoutReported=false;}else{motorStop();resetPID();}}else if(k=="PING"){lastPing=millis();timeoutReported=false;}else if(k=="SP")sp=v.toFloat();else if(k=="KP")kp=max(0.0f,v.toFloat());else if(k=="KI"){ki=max(0.0f,v.toFloat());if(ki==0)integral=0;}else if(k=="KD")kd=max(0.0f,v.toFloat());else if(k=="MAXPWM")maxPwm=constrain(v.toFloat(),0,255);else if(k=="ZERO"){noInterrupts();enc=0;interrupts();}}
void setup(){pinMode(PWM_CW,OUTPUT);pinMode(PWM_CCW,OUTPUT);motorStop();pinMode(ENC_A,INPUT_PULLUP);pinMode(ENC_B,INPUT_PULLUP);prevState=(digitalRead(ENC_A)<<1)|digitalRead(ENC_B);attachInterrupt(digitalPinToInterrupt(ENC_A),encISR,CHANGE);attachInterrupt(digitalPinToInterrupt(ENC_B),encISR,CHANGE);Serial.begin(115200);Serial.setTimeout(5);Serial.println("#PROTO,SPEED_PID,1");Serial.println("#ms,sp,rpm,error,P,I,D,pid_pwm,count");lastPing=millis();}
void loop(){while(Serial.available()){String s=Serial.readStringUntil('\n');command(s);}if(running&&millis()-lastPing>HOST_TIMEOUT_MS){running=false;motorStop();resetPID();if(!timeoutReported){Serial.println("#FAULT,HOST_TIMEOUT");timeoutReported=true;}}static uint32_t last=0;static long lastC=0;static float buf[8]={0},sum=0;static uint8_t bi=0,bn=0;uint32_t now=millis();if(now-last<SAMPLE_MS)return;float dt=(now-last)/1000.0f;last=now;noInterrupts();long c=enc;interrupts();long dc=c-lastC;lastC=c;float raw=(dc/COUNTS_PER_REV)*60.0f/dt;float old=buf[bi];buf[bi]=raw;sum+=raw-old;bi=(bi+1)%8;if(bn<8)bn++;float ma=sum/(bn?bn:1);lpf=.25f*ma+.75f*lpf;float e=sp-lpf,P=kp*e,D=0,u=0;if(!pidInit){prevPv=lpf;pidInit=true;}D=-kd*(lpf-prevPv)/dt;prevPv=lpf;float candI=integral+ki*e*dt,cand=P+candI+D;bool hi=cand>maxPwm,lo=cand<-maxPwm;if((!hi&&!lo)||(hi&&e<0)||(lo&&e>0))integral=candI;if(!running){u=0;integral=0;motorStop();}else{u=constrain(P+integral+D,-maxPwm,maxPwm);motorWrite(u);}Serial.print(now);Serial.print(',');Serial.print(sp,3);Serial.print(',');Serial.print(lpf,3);Serial.print(',');Serial.print(e,3);Serial.print(',');Serial.print(P,3);Serial.print(',');Serial.print(integral,3);Serial.print(',');Serial.print(D,3);Serial.print(',');Serial.print(u,3);Serial.print(',');Serial.println(c);}
