#include <Arduino.h>
const uint8_t EA=2,EB=3,CW=5,CCW=6; const float CPR=600.0f; const uint16_t TS=50;
volatile long enc=0; long prevEnc=0; unsigned long last=0; float rpmRaw=0,rpmLPF=0,alpha=.25,maBuf[5]={0};uint8_t mi=0;float maSum=0;
enum Mode{SPEED,POSITION};Mode mode=SPEED;float SP=100,Kp=.8,Ki=.4,Kd=.01,I=0,ePrev=0;bool runCtl=false;
void isrA(){bool a=digitalRead(EA),b=digitalRead(EB);enc+=(a==b)?1:-1;}
void motor(int u){u=constrain(u,-255,255);if(!runCtl)u=0;if(u>0){analogWrite(CW,u);analogWrite(CCW,0);}else if(u<0){analogWrite(CW,0);analogWrite(CCW,-u);}else{analogWrite(CW,0);analogWrite(CCW,0);}}
void cmd(String s){int c=s.indexOf(',');String k=c<0?s:s.substring(0,c),v=c<0?"":s.substring(c+1);float x=v.toFloat();if(k=="RUN")runCtl=x>0.5;else if(k=="SP")SP=x;else if(k=="KP")Kp=x;else if(k=="KI"){Ki=x;if(Ki==0)I=0;}else if(k=="KD")Kd=x;else if(k=="ALPHA")alpha=constrain(x,0,1);else if(k=="MODE"){mode=(v=="POSITION")?POSITION:SPEED;I=0;ePrev=0;}else if(k=="ZERO"){noInterrupts();enc=0;interrupts();prevEnc=0;} }
void setup(){Serial.begin(115200);pinMode(EA,INPUT_PULLUP);pinMode(EB,INPUT_PULLUP);pinMode(CW,OUTPUT);pinMode(CCW,OUTPUT);attachInterrupt(digitalPinToInterrupt(EA),isrA,CHANGE);Serial.println("ms,mode,sp,count,pos_deg,rpm_raw,rpm_ma,rpm_lpf,error,P,I,D,pid");}
void loop(){if(Serial.available()){String s=Serial.readStringUntil('\n');s.trim();cmd(s);}unsigned long now=millis();if(now-last<TS)return;float dt=(now-last)/1000.0f;last=now;noInterrupts();long c=enc;interrupts();rpmRaw=(c-prevEnc)/CPR/dt*60;prevEnc=c;maSum-=maBuf[mi];maBuf[mi]=rpmRaw;maSum+=rpmRaw;mi=(mi+1)%5;float rpmMA=maSum/5.0f;rpmLPF=alpha*rpmMA+(1-alpha)*rpmLPF;float pos=c/CPR*360.0f;float fb=(mode==SPEED)?rpmLPF:pos;float e=SP-fb;float P=(Kp==0)?0:Kp*e;float D=(Kd==0)?0:Kd*(e-ePrev)/max(dt,.001f);float trial=P+I+D,u=constrain(trial,-255.0f,255.0f);if(Ki==0)I=0;else if(runCtl&&!((u>=255&&e>0)||(u<=-255&&e<0)))I+=Ki*e*dt;I=constrain(I,-255.0f,255.0f);u=constrain(P+I+D,-255.0f,255.0f);ePrev=e;if(mode==POSITION&&abs(e)<0.5)u=0;motor((int)u);Serial.print(now);Serial.print(',');Serial.print(mode==SPEED?"SPEED":"POSITION");Serial.print(',');Serial.print(SP);Serial.print(',');Serial.print(c);Serial.print(',');Serial.print(pos,2);Serial.print(',');Serial.print(rpmRaw,2);Serial.print(',');Serial.print(rpmMA,2);Serial.print(',');Serial.print(rpmLPF,2);Serial.print(',');Serial.print(e,2);Serial.print(',');Serial.print(P,2);Serial.print(',');Serial.print(I,2);Serial.print(',');Serial.print(D,2);Serial.print(',');Serial.println(u,2);}
