%% P10 - Analyze encoder.csv generated by matlab_monitor_encoder.m
clear; clc; close all;

baseDir=fileparts(mfilename('fullpath'));
file=fullfile(baseDir,'output','encoder.csv');
if ~isfile(file), error('Missing %s. Run matlab_monitor_encoder.m first.',file); end
T=readtable(file);
req={'time_s','count','position_deg','rpm_raw','rpm_ma','rpm_lpf'};
assert(all(ismember(req,T.Properties.VariableNames)),'Unexpected encoder CSV columns.');

dt=diff(T.time_s);
fprintf('Samples: %d\n',height(T));
fprintf('dt min/median/max: %.6f / %.6f / %.6f s\n',min(dt),median(dt),max(dt));
fprintf('Count range: %g .. %g\n',min(T.count),max(T.count));
fprintf('Position range: %.3f .. %.3f deg\n',min(T.position_deg),max(T.position_deg));
fprintf('LPF RPM range: %.3f .. %.3f\n',min(T.rpm_lpf),max(T.rpm_lpf));
fprintf('Positive RPM samples: %d\n',nnz(T.rpm_lpf>0));
fprintf('Negative RPM samples: %d\n',nnz(T.rpm_lpf<0));

figure('Color','w');
tiledlayout(3,1);
nexttile; plot(T.time_s,T.count);grid on;ylabel('Count');
nexttile; plot(T.time_s,T.position_deg);grid on;ylabel('Position (deg)');
nexttile; plot(T.time_s,T.rpm_raw,T.time_s,T.rpm_ma,T.time_s,T.rpm_lpf,'LineWidth',1.0);grid on;xlabel('Time (s)');ylabel('RPM');legend('raw','MA','LPF');

outDir=fullfile(baseDir,'output');
exportgraphics(gcf,fullfile(outDir,'encoder_analysis.png'),'Resolution',180);
stats=table(height(T),min(dt),median(dt),max(dt),min(T.rpm_lpf),max(T.rpm_lpf), ...
    'VariableNames',{'samples','dt_min','dt_median','dt_max','rpm_min','rpm_max'});
writetable(stats,fullfile(outDir,'encoder_analysis_summary.csv'));
